-- Migration: Mark all existing leads as synthetic
-- All leads currently in the database were generated by the sync process
-- (generateLeadsForSource in /api/sync/execute) and are not real properties.
-- This migration flags them all as synthetic so they are hidden by default
-- across the entire app.

-- 1. Ensure the is_synthetic column exists (idempotent)
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS is_synthetic BOOLEAN NOT NULL DEFAULT false;

-- 2. Mark ALL existing leads as synthetic
--    (they were all generated by the deterministic seed-based sync process)
UPDATE public.leads
SET is_synthetic = true
WHERE is_synthetic = false OR is_synthetic IS NULL;

-- 3. Add a partial index for fast filtering of real leads (is_synthetic = false)
--    This makes all the .eq('is_synthetic', false) queries fast.
CREATE INDEX IF NOT EXISTS idx_leads_real
  ON public.leads (prospect_score DESC)
  WHERE is_synthetic = false;

-- 4. Add a partial index for synthetic leads (for admin/debug views)
CREATE INDEX IF NOT EXISTS idx_leads_synthetic
  ON public.leads (created_at DESC)
  WHERE is_synthetic = true;
