-- Store the supplied resume facts on the canonical candidate records so Vapi
-- receives candidate-specific context from Supabase at call time.

UPDATE public.candidates
SET
  phone = source.phone,
  professional_summary = source.professional_summary,
  work_experience = source.work_experience::jsonb,
  skills = source.skills::jsonb,
  relevant_systems = source.relevant_systems::jsonb,
  strengths = source.strengths::jsonb,
  concerns = source.concerns::jsonb,
  resume_highlights = source.resume_highlights::jsonb,
  resume_parsed_at = COALESCE(resume_parsed_at, now()),
  updated_at = now()
FROM (
  VALUES
    (
      'Brett Allen',
      '+17047785870',
      'Results-driven business professional with extensive experience in short-term rental operations, property management, and project execution. Known for streamlining processes, leading cross-functional teams, and delivering high-quality service across residential properties.',
      '[{"company":"Complete Rubbish","title":"Managing Partner","dates":"Dec 2023 - Present","evidence":["Launched a short-term rental trash company serving STR properties on Lake Norman.","Built a sustainable pricing program at three times local competitors."]},{"company":"Lakecations By AvantStay","title":"Director of Operations / General Manager","dates":"Oct 2023 - Mar 2025","evidence":["Oversaw operations for 60+ high-end properties.","Led integration of local operations into AvantStay.","Managed hiring, training, field teams, vendors, and housekeeping crews.","Doubled year-over-year revenue within 12 months to $18 million.","Led management companies against STR regulations in Iredell County."]},{"company":"Lakecations","title":"Director of Operations","dates":"Mar 2020 - Oct 2023","evidence":["Scaled STR operations from 10 to 40+ managed properties.","Implemented SOPs, maintenance schedules, and vendor relationships that improved efficiency by 40%.","Achieved a 4.9-star average review rating."]},{"company":"Laundrylux","title":"Sales Manager - Southeast","dates":"Oct 2016 - Jan 2019","evidence":["Managed B2B sales across eight southeastern states and exceeded regional targets by 25% annually.","Developed partnerships with laundromats, hospitality groups, and multi-housing operators.","Delivered technical presentations and ROI analyses."]}]',
      '["Property and vendor management","Short-term rental operations","Customer relationship management","Project management","Budgeting and cost control","Team leadership and training","Conflict resolution","Salesforce","Slack","Microsoft Office","Word","Excel"]',
      '["Salesforce","Slack","Microsoft Office","Word","Excel"]',
      '["Deep STR operations and high-end property management experience","Scaled managed-property operations and led cross-functional teams","Strong vendor, owner, guest-service, and regulatory experience","Demonstrated operational and sales leadership"]',
      '["Validate ability and motivation to shift from operations leadership into homeowner outreach and business development","Clarify personal ownership of homeowner acquisition, sales pipeline, and closing activities","Explore comfort with sustained phone-based outreach"]',
      '["60+ high-end properties","Grew a portfolio from 10 to 40+ properties","Doubled revenue to $18 million within 12 months","Improved operational efficiency by 40%","Achieved a 4.9-star guest review average","Exceeded B2B sales targets by 25% annually"]'
    ),
    (
      'Caitlyn Sorrells',
      '+18176945386',
      'Highly motivated professional with extensive experience in corporate housing, sales, lead generation, and property management. Experienced in pricing, guest satisfaction, maintenance coordination, inventory building, business-to-business outreach, and managing a corporate housing operation.',
      '[{"company":"Smallwood Corporate Housing","title":"National Director","dates":"Jul 2015 - Present","evidence":["Created pricing structures for units based on rent and utilities.","Answered leads from multiple sources and managed maintenance, utilities, renewals, guest satisfaction, inspections, and new-apartment setup.","Handled B2B calls and emails, marketing, inventory, platform accounts, and housekeeping scheduling.","Supervised the entire company."]},{"company":"Weatherford Property Management","title":"Assistant Property Manager","dates":"Feb 2010 - Jan 2015","evidence":["Handled leases, renewals, collections, legal violations, evictions, inspections, marketing, and occupancy goals.","Maintained customer service and answered multiline phone systems."]},{"company":"Palm Beach","title":"Store Sales Manager","dates":"Apr 2007 - Feb 2010","evidence":["Earned multiple promotions through strong sales and customer-service performance.","Held the number-one store position in a competitive DFW market."]}]',
      '["Corporate housing","Property management","Lead generation","Business-to-business calls","Sales","Customer service","Guest reservation booking","Property leasing","Closing sales","Phone communication","CRM software","HubSpot","Slack","Microsoft Outlook","Excel","Google Workspace"]',
      '["HubSpot","Slack","Microsoft Outlook","Excel","Google Workspace","CRM systems","Airbnb","Vrbo","Furnished Finder"]',
      '["Corporate housing and property-management leadership","Lead generation and B2B phone communication","Guest, owner, maintenance, and vendor coordination","Strong customer service and sales progression"]',
      '["Validate scope and measurable outcomes of national corporate-housing leadership","Explore conversion from inbound and existing leads to proactive homeowner outreach","Clarify experience presenting value to property owners and decision-makers"]',
      '["National Director of corporate housing","Managed pricing, leads, renewals, maintenance, utilities, inventory, and guest satisfaction","B2B calls and emails","Managed Airbnb, Vrbo, and Furnished Finder inventory","Promoted three levels in less than a year in sales management"]'
    ),
    (
      'Darlene Ciao',
      '+17027568283',
      'Sales and customer-service professional with experience in client services, retention, high-end sales, inside sales, phone sales, marketing, call centers, account management, scheduling, management, and extensive CRM use.',
      '[{"company":"Punchwork Law","title":"Legal Services Consultant - Sales","dates":"Jan 2026 - Present","evidence":["Conduct consultations, discovery, service and fee explanations, and follow-ups."]},{"company":"Melone Hatley Law","title":"Legal Services Consultant","dates":"Nov 2024 - Dec 2025","evidence":["Consulted with prospective clients and sold legal services based on needs."]},{"company":"Guardian HR","title":"Client Outreach and Retention Specialist","dates":"Nov 2022 - Nov 2024","evidence":["Made outreach calls, reintroduced services, researched clients, and managed accounts."]},{"company":"Federal Employee Service Association","title":"Client Services Specialist","dates":"Jan 2021 - Nov 2022","evidence":["Contacted and qualified leads and set appointments."]},{"company":"Holiday Inn Vacations","title":"Inside Sales Agent","dates":"Nov 2018 - Dec 2020","evidence":["Conducted timeshare presentations and tours and sold vacation products."]},{"company":"Anderson Business Advisors","title":"Client Services / Sales Agent","dates":"Nov 2014 - Nov 2018","evidence":["Handled client retention, sales, renewals, inbound and outbound calls."]}]',
      '["Sales","Client retention","Inside sales","Phone sales","Lead qualification","Appointment setting","Account management","Discovery","Follow-up","CRM","Salesforce","Zoho","Keap","Asana","HubSpot","Pipedrive"]',
      '["Salesforce","Zoho","Keap","Asana","HubSpot","Pipedrive","Benchmark","Google Suite","Microsoft Office","Outlook","Zoom","Slack"]',
      '["Consultative phone sales and discovery","Client retention and account management","Lead qualification and appointment setting","High-end and vacation-sales exposure","Broad CRM and sales-technology experience"]',
      '["Validate depth of homeowner and property-owner conversations","Explore consultative discovery and objection handling in a TRAVLR value proposition","Clarify metrics for call volume, appointments, conversion, and retention"]',
      '["Legal-services discovery and follow-up","Client outreach and retention","Vacation timeshare presentations and tours","Inbound and outbound calls","Extensive Salesforce, Zoho, Keap, HubSpot, and Pipedrive experience"]'
    ),
    (
      'Gina L. Mattivello',
      '+13397930755',
      'Highly driven inside and outside sales professional specializing in appointment setting, lead qualification, relationship building, phone and in-person closing, high-volume outreach, discovery, objection handling, and full-cycle sales.',
      '[{"company":"The Genesis Fit","title":"Sales / Partnership Specialist","dates":"Mar 2025 - Present","evidence":["Handle inbound inquiries and outreach campaigns, convert leads to appointments or closes, conduct discovery calls, manage CRM follow-ups, overcome objections, and improve conversion messaging."]},{"company":"Grayling Associates","title":"Executive Recruiter","dates":"Aug 2020 - Nov 2021","evidence":["Made 75-100 outbound calls per day, exceeded appointment KPIs, conducted discovery, closed deals by phone, and used CRM reporting to forecast pipeline health."]},{"company":"Vino Gelato","title":"Business Development Manager","dates":"Jul 2016 - Aug 2017","evidence":["Sourced, opened, and secured new accounts through prospecting and relationship building."]},{"company":"Wine Cask Imports","title":"Sales Representative / Business Development Manager","dates":"Mar 2005 - Aug 2007","evidence":["Generated 95% of sales from cold calling, opened 87 accounts, and increased revenue by $450,000."]},{"company":"American Industrial Supply","title":"Sales Representative","dates":"Mar 1998 - Feb 2000","evidence":["Revitalized a dormant territory through cold calling and new-account development."]}]',
      '["High-volume outbound calling","Pipeline management","Phone closing","Discovery and needs analysis","Objection handling","Appointment setting","Follow-up sequences","KPI ownership","Rapport building","Active listening","CRM systems","Sales scripts"]',
      '["Custom CRM","CRM reporting","MS Office","Salesforce-compatible pipeline workflows"]',
      '["Exceptional high-volume phone and outbound-sales discipline","Strong discovery, objection handling, and closing evidence","Documented pipeline, appointment, and revenue outcomes","Experienced with relationship building and consultative selling"]',
      '["Validate ability to adapt from B2B and consumer sales to luxury homeowner conversations","Explore how she balances high call volume with a white-glove homeowner experience","Probe depth of STR/property-management knowledge and learning plan"]',
      '["75-100 outbound calls per day","95% of Wine Cask sales from cold calling","Opened 87 new accounts","Increased revenue by $450,000","Opened a $4,000 retail account from a walk-in cold call","Exceeded appointment-setting KPIs"]'
    ),
    (
      'Jessica Thrasher',
      '+15134446552',
      'Experienced business professional with real-estate, property-management, marketing, operations, customer service, project management, executive administration, and sales experience. Former U.S. Marine with strong organization, communication, and leadership background.',
      '[{"company":"Thrasher Marketing LLC","title":"Owner","dates":"Apr 2021 - Present","evidence":["Runs marketing services, client consultations, campaigns, analytics, budgeting, and client relationships."]},{"company":"Signature Real Estate","title":"Associate Real Estate Agent","dates":"Apr 2018 - Dec 2021","evidence":["Worked with home buyers, conducted needs analysis, participated in cold calling and events, managed documents, and handled client marketing."]},{"company":"Marys Management","title":"Customer Service Representative","dates":"Jun 2019 - Feb 2020","evidence":["Handled inbound and outbound calls, customer support, work orders, and performance goals."]},{"company":"Park Lane Condominium Association","title":"Assistant Property Manager","dates":"May 2016 - Jun 2019","evidence":["Supported a 354-unit high-rise with a $2 million operating budget, vendor bids, resident communication, projects, hiring, onboarding, and compliance."]},{"company":"LONG Building Technologies","title":"Administrative Assistant III","dates":"Jan 2012 - Nov 2014","evidence":["Used Salesforce for B2B HVAC and plumbing bid intake and communicated with sales and project teams."]},{"company":"U.S. Marine Corps","title":"Personnel / Administrative Clerk","dates":"May 2006 - Dec 2009","evidence":["Managed records, training, correspondence, schedules, and administrative programs for large personnel groups."]}]',
      '["Real estate","Property management","Marketing","Operations management","Customer service","Project management","Sales","Cold calling","Client needs analysis","Salesforce","CRM applications","Google Suite","Public speaking","Personnel management"]',
      '["Salesforce","ZenDesk","Slack","Ring Central","DocuSign","CTM Contracts","Dropbox","Google Suite"]',
      '["Property-management and real-estate client experience","Strong organization, compliance, and operations background","Marketing and client-relationship experience","Leadership and disciplined administrative execution"]',
      '["Validate direct homeowner acquisition and phone-sales experience","Explore transition from property operations and real estate into sustained outreach","Clarify measurable sales, conversion, and pipeline outcomes"]',
      '["Managed a 354-unit high-rise with a $2 million operating budget","Colorado real-estate agent and broker credentials","Cold calling and client needs analysis","Salesforce B2B bid-management experience","U.S. Marine Corps leadership and records-management experience"]'
    ),
    (
      'Karissa Crooks',
      '+14432052906',
      'Business and property-management professional with direct short-term rental operations, owner lead management, licensing, revenue management, new-home sales, and luxury hospitality experience.',
      '[{"company":"Brookfield Residential","title":"New Home Sales Manager","dates":"Aug 2023 - Present","evidence":["Sells new-construction homes, builds realtor and local-business relationships, presents communities, and follows up with prospective buyers across multiple channels."]},{"company":"ESVR Vacation Rentals","title":"Assistant General Manager / Property Manager","dates":"Nov 2020 - Aug 2023","evidence":["Managed STR operations, vendors, luxury check-in and check-out, Airbnb, Vrbo, Track CRM, owner leads in Vintory, property onboarding, licensing with Talbot and Dorchester County, revenue goals, pricing, minimum stays, and owner reports."]},{"company":"Jack Lingo Realtor","title":"Vacation Rentals Property Manager / Real Estate Agent","dates":"Mar 2018 - Mar 2020","evidence":["Managed vacation-rental listings, inspections, guest claims, leases, pricing, HOA communication, maintenance, and after-hours issues."]},{"company":"Keller Williams Realty","title":"Vacation Rentals Property Manager / Real Estate Agent","dates":"Apr 2017 - Mar 2018","evidence":["Managed STR operations, listings, pricing, leases, inspections, staff training, and homeowner presentations."]},{"company":"Seascape Property Management","title":"Assistant General Manager","dates":"Mar 2013 - Apr 2017","evidence":["Managed clubhouse operations, events, vendors, residents, inspections, potential-buyer tours, and owner registration."]},{"company":"Walt Disney World Resort","title":"Front Office Manager Intern","dates":"May 2012 - May 2013","evidence":["Supported front desk, concierge, reservations, guest satisfaction, accounting, and staff development."]}]',
      '["Short-term rental operations","Property management","Homeowner presentations","Owner lead management","Revenue management","Pricing","STR licensing","Sales","Marketing","Hospitality","Salesforce","Vintory","Track","Beyond Pricing","Key Data","Breezeway","Barefoot","StayNTouch","Signal","DocuSign"]',
      '["Salesforce","Vintory","Track CRM","Beyond Pricing","Key Data","Breezeway","Barefoot","StayNTouch","Signal","DocuSign","Newstar Sales"]',
      '["Deep vacation-rental and property-management experience","Direct owner-lead and onboarding experience","Strong revenue management and regulatory knowledge","Homeowner-facing sales and presentation experience","High-touch hospitality and operations background"]',
      '["Validate sustained outbound homeowner-acquisition volume and metrics","Explore personal ownership from first owner conversation through signed management agreement","Probe transition from operations and new-home sales into dedicated business development"]',
      '["Managed owner leads in Vintory CRM","Handled Talbot and Dorchester County STR licensing","Set occupancy goals, adjusted pricing, and provided owner reports","Presented vacation-rental listings to new homeowners","Managed Airbnb, Vrbo, Track, and multiple property operations"]'
    ),
    (
      'Kelli Winkel',
      '+14482057573',
      'Business-development leader with more than 20 years of luxury vacation-rental, property-management, consultative selling, homeowner recruitment, sales-pipeline, and owner-relationship experience.',
      '[{"company":"Grand Welcome","title":"Business Development Director","dates":"Jan 2021 - Present","evidence":["Directs business development across seven markets, recruits private properties, manages the full sales pipeline, and closes vacation-rental property agreements."]},{"company":"IPG Florida Homes","title":"Director of Business Development","dates":"Aug 2015 - Jan 2021","evidence":["Recruited homeowners, developers, and investors, presented to brokers and agents, negotiated contracts, and managed complex decision-maker relationships."]},{"company":"HWA - Home Warranty of America","title":"Territory Manager","dates":"Jan 2013 - Aug 2015","evidence":["Managed sales and business development across the Florida Panhandle, built a CRM-tracked high-volume outreach funnel, and acquired new accounts through consultative selling."]},{"company":"Emerald Coast Vacation Rentals","title":"Director of Sales","dates":"Apr 2005 - Jan 2013","evidence":["Recruited property owners into an STR program and expanded the portfolio from 40 to 700 units.","Managed sales, business development, reservations, advertising, housekeeping, and owner relationships."]},{"company":"Watersound Beach Club","title":"Membership Sales Manager","dates":"May 2000 - Apr 2005","evidence":["Sold high-value memberships averaging $30,000 to property owners and real-estate agents."]}]',
      '["Business development","Homeowner recruitment","Luxury vacation rentals","Property management","Consultative selling","Contract negotiation","Sales presentations","CRM","Lead generation","Pipeline management","Account management","Closing sales","Relationship management"]',
      '["CRM software","Sales pipeline management","Sales presentations","Real-estate and property-management systems"]',
      '["Exceptional direct fit for homeowner acquisition and STR business development","20+ years of luxury vacation-rental experience","Scaled an STR portfolio from 40 to 700 units","Strong consultative selling, presentations, negotiation, and closing"]',
      '["Validate current pipeline, activity, and closing metrics across seven markets","Explore how she adapts a mature sales approach to TRAVLRs positioning and warm-lead process","Probe examples of difficult homeowner objections and retention conversations"]',
      '["Recruited private properties across seven markets","Managed full sales pipeline through closing","Grew Emerald Coast portfolio from 40 to 700 units","Sold memberships averaging $30,000","Built CRM-tracked high-volume outreach funnels"]'
    ),
    (
      'Margo Johnson',
      '+19172915361',
      'Business-development and sales specialist with B2B and B2C experience, high-volume outbound calling, product demos, CRM expertise, full-cycle sales, account management, and relationship building.',
      '[{"company":"Squeaky Ventures / Heavy Hammer / Qazzoo","title":"Business Development Representative","dates":"2018 - Present","evidence":["Placed 300+ outbound cold calls per day to real-estate businesses, qualified leads, ran product demos, partnered with account executives to close 6+ deals per week, and ranked in the top three BDRs."]},{"company":"Squeaky Ventures / Bespoke Cyber / RedAccess.io","title":"Business Development Lead","dates":"2018 - Present","evidence":["Created messaging strategies, executed multichannel outreach, and built a qualified pipeline exceeding $300,000 in 90 days."]},{"company":"Squeaky Ventures / Investor-Entrepreneur Client","title":"Business Development and Research Consultant","dates":"2018 - Present","evidence":["Managed full-cycle B2B sales, increased account volume threefold within six months, secured direct sales and a distributor partnership."]},{"company":"Umbrelli","title":"Founder","dates":"Aug 2008 - Dec 2012","evidence":["Created an inside-sales process that secured Neiman Marcus as the first client and developed customer-facing retail training and trunk shows."]},{"company":"Wall Street Webcasting","title":"Conference Director / Consultant","dates":"Oct 2005 - May 2011","evidence":["Managed more than 20 investment-bank accounts, maintained 100% retention, secured an enterprise partnership contributing to a 10% monthly sales lift, and trained 30+ consultants per quarter."]}]',
      '["Business development","B2B and B2C sales","Outbound calling","Product demos","Lead qualification","Full-cycle sales","Pipeline management","Closing","Account management","Training","Market research","HubSpot","Salesforce","VanillaSoft","Pipedrive","ZoomInfo"]',
      '["HubSpot","Salesforce","VanillaSoft","Pipedrive","Jira","Monday","ZoomInfo","Zoom","Google Workspace","Adobe Creative Suite"]',
      '["Exceptional high-volume outbound and BDR performance","Full-cycle B2B sales and C-level relationship experience","Strong CRM, messaging, demo, pipeline, and training skills","Documented retention, partnership, and revenue outcomes"]',
      '["Validate adaptation from SaaS and B2B prospecting to luxury homeowner conversations","Explore how high-volume methods can preserve a consultative, relationship-first experience","Probe STR and property-management knowledge and learning plan"]',
      '["300+ outbound calls per day","6+ deals closed per week","Top-three BDR ranking","$300,000+ qualified pipeline in 90 days","Tripled account volume in six months","100% retention across 20+ investment-bank accounts","10% monthly sales lift from enterprise partnership"]'
    )
) AS source(full_name, phone, professional_summary, work_experience, skills, relevant_systems, strengths, concerns, resume_highlights)
WHERE public.candidates.full_name = source.full_name;