-- Migration: Flag and hide all synthetic/mismatched leads
-- Timestamp: 20260903050000
-- Purpose:
--   1. Mark leads with placeholder/listing-ID addresses as is_synthetic=true
--   2. Mark leads with example.com / synthetic.travlr listing URLs as is_synthetic=true
--   3. Mark leads generated by the refresh service (id starts with 'refresh-') as is_synthetic=true
--   4. Mark leads where the zip code does not match the city/state (cross-market mismatches)
--      by flagging the known bad zip pattern: zip='80202' but state is not CO
-- All synthetic leads are already excluded from normal queries via .neq('is_synthetic', true)

-- Step 1: Flag leads with placeholder/listing-ID addresses
UPDATE public.leads
SET is_synthetic = true,
    updated_at = now()
WHERE is_synthetic IS DISTINCT FROM true
  AND (
    address IS NULL
    OR address = ''
    OR address ~* '^(Zillow|HotPads|Apartments\.com|Craigslist|Facebook Marketplace|Realtor\.com|LoopNet|Trulia|Redfin|MLS|Airbnb|VRBO|Direct|Referral|Other|Unknown)\s+Listing\s+#\d+$'
    OR address ~* '^Imported Property'
  );

-- Step 2: Flag leads with fake/generated listing URLs (example.com, synthetic.travlr, etc.)
UPDATE public.leads
SET is_synthetic = true,
    updated_at = now()
WHERE is_synthetic IS DISTINCT FROM true
  AND listing_url IS NOT NULL
  AND listing_url != ''
  AND (
    listing_url ~* '^https?://(www\.)?example\.com'
    OR listing_url ~* '^https?://(www\.)?placeholder\.com'
    OR listing_url ~* '^https?://(www\.)?synthetic\.travlr'
    OR listing_url ~* '^https?://(www\.)?test\.com'
    OR listing_url ~* '^https?://localhost'
  );

-- Step 3: Flag leads generated by the refresh service (stable IDs start with 'refresh-')
UPDATE public.leads
SET is_synthetic = true,
    updated_at = now()
WHERE is_synthetic IS DISTINCT FROM true
  AND id LIKE 'refresh-%';

-- Step 4: Flag cross-market mismatches — zip code from one city used with a different state.
-- The known bad pattern is Denver zip codes (80202-80299) on non-CO leads.
UPDATE public.leads
SET is_synthetic = true,
    updated_at = now()
WHERE is_synthetic IS DISTINCT FROM true
  AND state IS NOT NULL
  AND state != 'CO'
  AND zip IS NOT NULL
  AND zip ~ '^802[0-9]{2}$';

-- Step 5: Flag leads where address contains a street name from the Denver pool
-- but the state is not CO — these are the "9365 Lakeview Ct, Denver, CO 80202"
-- style mismatches where a Denver address was reused in another city/state.
-- We identify them by the combination of a CO zip AND a non-CO state.
UPDATE public.leads
SET is_synthetic = true,
    updated_at = now()
WHERE is_synthetic IS DISTINCT FROM true
  AND state IS NOT NULL
  AND state != 'CO'
  AND city IS NOT NULL
  AND city ~* '^(Denver|Aspen|Breckenridge|Vail)$';

-- Step 6: Ensure the is_synthetic column has a default of false for new rows
ALTER TABLE public.leads
  ALTER COLUMN is_synthetic SET DEFAULT false;

-- Step 7: Create an index on is_synthetic for fast filtering (idempotent)
CREATE INDEX IF NOT EXISTS idx_leads_is_synthetic ON public.leads (is_synthetic)
  WHERE is_synthetic = true;

-- Verification summary (informational only)
DO $$
DECLARE
  synthetic_count INTEGER;
  real_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO synthetic_count FROM public.leads WHERE is_synthetic = true;
  SELECT COUNT(*) INTO real_count FROM public.leads WHERE is_synthetic IS DISTINCT FROM true;
  RAISE NOTICE 'After migration: % synthetic leads hidden, % real leads visible', synthetic_count, real_count;
END $$;
