import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

// Use service role key to bypass RLS for admin server-side operations.
// SUPABASE_SERVICE_ROLE_KEY must be set in .env — never expose it client-side.
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!serviceRoleKey) {
  console.warn(
    '[agent-invite/create] SUPABASE_SERVICE_ROLE_KEY is not set. ' +
    'Falling back to anon key — inserts will be subject to RLS and may fail for non-admin sessions.'
  );
}

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  serviceRoleKey || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  serviceRoleKey
    ? { auth: { autoRefreshToken: false, persistSession: false } }
    : {}
);

export async function POST(req: NextRequest) {
  try {
    const { firstName, lastName, email, assignedPortfolios, invitedBy } = await req.json();

    if (!firstName || !lastName || !email) {
      return NextResponse.json({ error: 'First name, last name, and email are required.' }, { status: 400 });
    }

    // Check for existing active invite for this email
    const { data: existing } = await supabaseAdmin
      .from('agent_invites')
      .select('id, status, expires_at')
      .eq('email', email.toLowerCase())
      .in('status', ['invited'])
      .single();

    if (existing) {
      const isStillValid = new Date(existing.expires_at) > new Date();
      if (isStillValid) {
        return NextResponse.json({ error: 'An active invite already exists for this email. Revoke it first or wait for it to expire.' }, { status: 409 });
      }
    }

    // Create the invite record — token is auto-generated by DB default
    const { data: invite, error: insertErr } = await supabaseAdmin
      .from('agent_invites')
      .insert({
        email: email.toLowerCase(),
        first_name: firstName,
        last_name: lastName,
        assigned_portfolios: assignedPortfolios || [],
        role: 'agent',
        invited_by: invitedBy || null,
        status: 'invited',
      })
      .select('id, invite_token, email, first_name, last_name')
      .single();

    if (insertErr || !invite) {
      return NextResponse.json({ error: insertErr?.message || 'Failed to create invite.' }, { status: 500 });
    }

    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://app.staytrvlr.com';
    const inviteLink = `${siteUrl}/invite/${invite.invite_token}`;
    const fullName = `${firstName} ${lastName}`;

    // Send invite email
    const { error: emailErr } = await resend.emails.send({
      from: 'TRAVLR Pro <info@staytrvlr.com>',
      to: invite.email,
      subject: `You've been invited to join TRAVLR Pro`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 520px; margin: 0 auto; padding: 40px 24px; background: #ffffff;">
          <div style="margin-bottom: 32px;">
            <h1 style="font-size: 24px; font-weight: 700; color: #111827; margin: 0 0 8px;">Welcome to TRAVLR Pro, ${firstName}!</h1>
            <p style="color: #6b7280; font-size: 15px; margin: 0; line-height: 1.6;">
              You've been invited to join the TRAVLR Pro platform as a <strong>Homeowner Outreach &amp; Business Development Agent</strong>.
            </p>
          </div>
          <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px; margin-bottom: 28px;">
            <p style="color: #374151; font-size: 14px; margin: 0 0 4px; font-weight: 600;">What happens next:</p>
            <ol style="color: #6b7280; font-size: 14px; margin: 8px 0 0; padding-left: 20px; line-height: 1.8;">
              <li>Click the button below to set up your account</li>
              <li>Create your password</li>
              <li>Complete the mandatory platform orientation tour</li>
              <li>Start working your leads</li>
            </ol>
          </div>
          <a href="${inviteLink}" style="display: inline-block; background: #2563eb; color: #ffffff; font-size: 15px; font-weight: 600; padding: 14px 28px; border-radius: 10px; text-decoration: none; margin-bottom: 28px;">
            Set Up My Account →
          </a>
          <p style="color: #9ca3af; font-size: 13px; margin-bottom: 4px;">
            Or copy this link: <span style="color: #374151; font-family: monospace; font-size: 12px;">${inviteLink}</span>
          </p>
          <p style="color: #d1d5db; font-size: 12px; margin-top: 24px;">
            This invite expires in 7 days. If you didn't expect this, you can safely ignore it.
          </p>
          <hr style="border: none; border-top: 1px solid #f3f4f6; margin: 24px 0;" />
          <p style="color: #d1d5db; font-size: 11px; margin: 0;">TRAVLR Pro · Short-Term Rental Prospect Platform</p>
        </div>
      `,
    });

    return NextResponse.json({
      success: true,
      inviteId: invite.id,
      inviteLink,
      emailSent: !emailErr,
      emailError: emailErr?.message || null,
    });
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Unknown error' }, { status: 500 });
  }
}
